# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Muscle.destroy_all
Exercise.destroy_all

chest = Muscle.create!(title: 'Chest', photoUrl: 'http://build-muscle-101.com/wp-content/uploads/2014/12/chest-muscles.jpg')
arms = Muscle.create!(title: 'Arms', photoUrl: 'http://www.muscleblitz.com/wp-content/uploads/2014/01/arm-diagram.jpg')
legs = Muscle.create!(title: ' Legs', photoUrl: 'https://s-media-cache-ak0.pinimg.com/originals/5d/05/85/5d0585aa0a7ecf0a51202bdc3d8746bd.jpg')
back = Muscle.create!(title: 'Back', photoUrl: 'http://www.wedocable.com/photo/370x250-lower-back-muscles-diagram-1994003.jpeg')

chest.exercises.create!(workout: 'Bench Press', photoUrl: 'http://demandware.edgesuite.net/aaxp_prd/on/demandware.static/-/Sites-Predator-Library/default/dw96b4f9c2/images/articles/Barbell_Bench_Press.png', description: 'A bodybuilding and weightlifting exercise in which a lifter lies on a bench with feet on the floor and raises a bar with both arms.', video: 'https://www.youtube.com/watch?v=DD0ZSeV90iQ')
chest.exercises.create!(workout: 'Dumbbell Fly', photoUrl: 'http://cdn.nlfitsoci-elmley.savviihq.com/wp-content/uploads/2012/04/dumbbell_flyes.jpg', description: 'Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. ... Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other.', video: 'https://www.youtube.com/watch?v=eozdVDA78K0')
chest.exercises.create!(workout: 'Push ups', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Pushup.png', description: 'An exercise in which a person lies facing the floor and, keeping their back straight, raises their body by pressing down on their hands.', video: 'https://www.youtube.com/watch?v=IODxDxX7oi4')
chest.exercises.create!(workout: 'Incline Bench', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Incline_Barbell_Bench_Press.png', description: 'The bench press is an upper body strength training exercise that consists of pressing a weight upwards from a supine position. ... A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.', video: 'https://www.youtube.com/watch?v=DbFgADa2PL8')
chest.exercises.create!(workout: 'Cable Fly', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Standing_Cable_Fly.png', description: ' A Cable fly or Cable flye is a strength training exercise in which the hand and arm move through an arc while the elbow is kept at a constant angle. Flies are used to work the muscles of the upper body.', video: 'https://www.youtube.com/watch?v=-kNpoo25ywk')

arms.exercises.create!(workout: 'Straight Bar Curl', photoUrl: 'http://monthlymale.com/wp-content/uploads/2016/03/straight-bar-curls.png', description: 'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.', video: 'https://www.youtube.com/watch?v=LY1V6UbRHFM')
arms.exercises.create!(workout: 'Skull Crushers', photoUrl: 'http://monthlymale.com/wp-content/uploads/2016/03/skullcrushers1.png', description: 'Lie on a flat bench with feet on the ground and head hanging just off the top of the bench, so that the edge of the bench rests in the pit between neck and head.
Take the barbell with an overhand grip (palms away from body) and hold it out above the head so that the arms are supporting the weight. Do not hold the arms straight over the face at 12 oclock, but rather at an angle more like 10 oclock, with feet at 3 oclock. All of the weight should be on the triceps.
Now bend the arms at the elbow, bringing the bar down close to the top of the forehead.
Keep the elbows in the same position, do not let them sway outward.
Press back up to starting 10 o’clock position.', video: 'https://www.youtube.com/watch?v=d_KZxkY_0cM')
arms.exercises.create!(workout: 'Hammer Curls', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Hammer_Curls.png', description: 'Position two dumbbells to sides, palms facing in, arms straight. With elbows to sides, raise one dumbbell until forearm is vertical and thumb faces shoulder. Lower to original position and repeat with alternative arm.', video: 'https://www.youtube.com/watch?v=zC3nLlEvin4')
arms.exercises.create!(workout: 'Preacher Curls', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Ez-bar_Precher_Curl.png', description: ' A weightlifting exercise for the biceps in which a barbell is lifted by flexing the elbows, with the upper arms resting on an angled bench.', video: 'https://www.youtube.com/watch?v=DoCWeUBA0Gs')
arms.exercises.create!(workout: 'Tricep Pushdown', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Triceps_Pushdown.png', description: 'This movement is performed with a cable push down machine. You may have to attach a small straight or angled bar to it. Also, be sure to select a weight by moving the pin in the hole of the weight desired in the weight stack.
Stand with your feet shoulder width apart and slightly bent to relieve stress from your lower back.
Grasp the bar with an overhand grip, as well keep your thumbs over the bar rather than over top. Keep your elbows close to your sides. Dont lean forward, keep straight posture. Press the bar down until your arm is fully extended. Contract your triceps.
Slowly lower the weight back down to a position greater than 90 degrees, repeat the movement.', video: 'https://www.youtube.com/watch?v=2-LAMcpzODU')

legs.exercises.create!(workout: 'Squat', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Barbell-Squat.png', description: 'Begin with the barbell supported on top of the traps. The chest should be up and the head facing forward. Adopt a hip-width stance with the feet turned out as needed.
Descend by flexing the knees, refraining from moving the hips back as much as possible. This requires that the knees travel forward. Ensure that they stay align with the feet. The goal is to keep the torso as upright as possible.
Continue all the way down, keeping the weight on the front of the heel. At the moment the upper legs contact the lower legs reverse the motion, driving the weight upward.', video: 'https://www.youtube.com/watch?v=1xMaFs0L3ao')
legs.exercises.create!(workout: 'Bulgarian Split Squat', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Bulgarian_Split_Squat.png', description: 'Stand lunge-length in front of a bench. Hold a dumbbell in each hand and rest the top of your left foot on the bench behind you. Lower your body until your rear knee nearly touches the floor and your front thigh is parallel to the floor.', video: 'https://www.youtube.com/watch?v=2C-uNgKwPLE')
legs.exercises.create!(workout: 'Leg Curl', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Seated_Leg_curl_M_WorkoutLabs.png', description: 'The leg curl is an isolation exercise that targets the hamstring muscles. The exercise involves flexing the lower leg against resistance towards the buttocks.', video: 'https://www.youtube.com/watch?v=ELOCsoDSmrg')
legs.exercises.create!(workout: 'Leg Press', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Leg_press_M_WorkoutLabs.png', description: 'You will sit on the machine and put your feet about shoulder width apart. Then push the weight up, unlock it and come down. Push back up and do it again', video: 'https://www.youtube.com/watch?v=Aq5uxXrXq7c')
legs.exercises.create!(workout: 'Goblet Squat', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Goblet_squat.png', description: 'Take a kettle ball or dumb bell and hold it in front of your chest close to your body, then perform your squat', video: 'https://www.youtube.com/watch?v=MeIiIdhvXT4')

back.exercises.create!(workout: 'Pull Up', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Pullup.png', description: 'A pull-up is an upper-body compound pulling exercise. Although it can be performed with any grip, in recent years some have used the term to refer more specifically to a pull-up performed with a palms-forward position.', video: 'https://www.youtube.com/watch?v=oblWkK88_Vw')
back.exercises.create!(workout: 'One Armed Row', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/One_Arm_Dumbbell_Row.png', description: 'Lean down onto a bench with one dumb bell. Your back will be flat. With one arm, take the dumb bell and extend it towards the floor, pull it back up, repeat', video: 'https://www.youtube.com/watch?v=1gOYkpfT9Hc')
back.exercises.create!(workout: 'Lat Pull Down', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Wide-Grip_Lat_Pulldown.png', description: 'Set weight then sit on machine. Extend your arms to grasp the bar. Pull down towards you, hold and then extend back up. Grips can be changed for different targets of back muscles', video: 'https://www.youtube.com/watch?v=JEb-dwU3VF4')
back.exercises.create!(workout: 'Bentover Row', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Bent_Over_Barbell_Row.png', description: 'Take a bar and put weight on. Bend your knees slightly and lean forward. Make sure your spine in straight and not bent over. Grasp bar and pull into you, release and do it again.', video: 'https://www.youtube.com/watch?v=4xq3BsKTzYo')
back.exercises.create!(workout: 'Seated Row', photoUrl: 'http://workoutlabs.com/wp-content/uploads/watermarked/Seated_Low_Cable_Row.png', description: 'Sit on machine after changing weight. Grab handle or bar with both hands. Lean slightly back and pull the weight into you.', video: 'https://www.youtube.com/watch?v=GZbfZ033f74')
